name: BlockRegen
main: nl.Aurorion.BlockRegen.Main
version: 3.6.0
authors: [Aurorion, Wertik1206]
softdepend: [Vault, WorldEdit, Towny, Jobs, GriefPrevention]

commands:
  blockregen:
    aliases: [br]
    description: Main plugin command