name: BlockRegen
main: nl.Aurorion.BlockRegen.Main
version: 3.6.0-b7
authors: [Aurorion, Wertik1206]
softdepend: [Vault, WorldGuard, WorldEdit, Towny, GriefPrevention, Multiverse-Core, Jobs]
api-version: 1.13
commands:
  blockregen:
    aliases: [br, blockr, bregen, breg]
    description: Main plugin command