name: BlockRegen
main: nl.Aurorion.BlockRegen.Main
version: 3.6.0-b5
authors: [Aurorion, Wertik1206]
softdepend: [Vault, WorldGuard, WorldEdit, Towny, Jobs, GriefPrevention, Multiverse-Core]
api-version: 1.13
commands:
  blockregen:
    aliases: [br]
    description: Main plugin command