name: BlockRegen
main: nl.Aurorion.BlockRegen.Main
version: 3.6.0-LEGACY-b4
authors: [Aurorion, Wertik1206]
softdepend: [Vault, WorldEdit, Towny, Jobs, GriefPrevention, Multiverse-Core]
commands:
  blockregen:
    aliases: [br]
    description: Main plugin command